<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>15d2cfecdfc2514966918ffe</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-12 23:21:27</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>situation_manager.py:230</categoryid><desyncid>15d2cfecdfc2514966918ffe</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (RuntimeError: Set changed size during iteration)&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5544, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5556, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7594, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6574, in _trigger_interaction_complete_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 984, in handle_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 948, in _increment_completion_count&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_goal.py", line 890, in _on_goal_completed&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\situation_manager.py", line 230, in __exit__&#13;&#10;RuntimeError: Set changed size during iterationrtim=0&#13;&#10;Client Session Time: 17.99&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
</root>