<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:55:35</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:55:41</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 376, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:55:44</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:55:52</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:03</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:10</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:26</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:30</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:36</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:54</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:57</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:56:59</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:57:01</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:57:06</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1499da68691e57f36692d865</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-07-13 21:57:07</createtime><buildsignature>Local.Unknown.Unknown.1.107.151.1020-1.300.000.182.Release</buildsignature><categoryid>test_variants.py:3248</categoryid><desyncid>1499da68691e57f36692d865</desyncid><systemconfig/><screenshot/><desyncdata>Exception during call to test method on &lt;class 'sims4.tuning.instances.jungleGymBoat_AdultAttack'&gt; (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 496, in _process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_service.py", line 433, in _update_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 253, in run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1385, in _run_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 1802, in _score_object_interactions_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\autonomy\autonomy_modes.py", line 969, in _test_aop&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\aop.py", line 166, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 2821, in test&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\tests.py", line 720, in run_tests&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\resolver.py", line 145, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\caches.py", line 296, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3268, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\test_variants.py", line 3248, in matching_interaction_in_si_state&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 64.13&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,248,0,5761&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 11 10.0.22631 GPU: AMD Radeon (TM) Graphics aticfx64.dll 31.0.21024.11002, GUID: D7B71EE2-56A7-11CF-E05E-F5226AC2D235&#13; &#10;</desyncdata></report>
</root>